server:
    port: 8081
    servlet:
        context-path: /econcilia/api

spring:
    datasource:
        url: jdbc:mysql://${mysql.url}/${mysql.schema}?useSSL=true&serverTimezone=UTC&characterEncoding=UTF-8
        username: ${mysql.username}
        password: ${mysql.password}
        hikari:
            auto-commit: false
            connection-timeout: 250
            max-lifetime: 600000
            maximum-pool-size: 20
            minimum-idle: 10
            pool-name: master
    jpa:
        open-in-view: false
        show-sql: true
        hibernate:
            ddl-auto: none
        properties:
            "[hibernate.dialect]": org.hibernate.dialect.MySQL5InnoDBDialect
            "[hibernate.generate_statistics]": false
            "[hibernate.connection.provider_disables_autocommit]": true

    ifood:
        client-id: ${ifood.clientid}
        client-secret: ${ifood.clientsecret}
    urls:
        url-ordens: https://merchant-api.ifood.com.br/order/v1.0/events:polling
        url-comerciantes: https://merchant-api.ifood.com.br/merchant/v1.0/merchants
        url-financeiro: https://merchant-api.ifood.com.br/financial/v2.0/merchants/
        url-ordens-detalhes: https://merchant-api.ifood.com.br/order/v1.0/orders/
        url-autenticacao: https://merchant-api.ifood.com.br/authentication/v1.0/oauth/token
