 CREATE TABLE `consolidado` (
	`id` bigint NOT NULL AUTO_INCREMENT,
	`periodo` DATE NOT NULL,
	`quantidade_venda` NUMERIC(10) NOT NULL DEFAULT 0,
	`ticket_medio` NUMERIC(10,3) NOT NULL DEFAULT 0.00,
	`total_bruto` NUMERIC(10,3) NOT NULL DEFAULT 0.00,
	`total_cancelado` NUMERIC(10,3) NOT NULL DEFAULT 0.00,
	`total_comissao` NUMERIC(10,3) NOT NULL DEFAULT 0.00,
	`total_liquido` NUMERIC(10,3) NOT NULL DEFAULT 0.00,
	`total_promocao` NUMERIC(10,3) NOT NULL DEFAULT 0.00,
	`total_recebido` NUMERIC(10,3) NOT NULL DEFAULT 0.00,
	`total_taxa_entrega` NUMERIC(10,3) NOT NULL DEFAULT 0.00,
	`total_transacao_pagamento` NUMERIC(10,3) NOT NULL DEFAULT 0.00,
	`total_taxa_servico` NUMERIC(10,3) NOT NULL DEFAULT 0.00,
	`total_repasse` NUMERIC(10,3) NOT NULL DEFAULT 0.00,
	`total_taxa_manutencao` NUMERIC(10,3) DEFAULT 0.00,
	`empresa_id` bigint NOT NULL,
	`operadora_id` bigint NOT NULL,
	PRIMARY KEY (`id`)
);